#timemodule
print("....................")
import time
print("current time in sec",time.time())
print("....................")
print("current time:",time.ctime())
print("....................")
print("current time after 30 sec:",time.ctime(time.time()+30))
print("....................")
t=time.localtime()
print("time:",t)
print("....................")
print("current year:",t.tm_year)
print("current month:",t.tm_mon)
print("current day:",t.tm_mday)
print("current hour:",t.tm_hour)
print("current min:",t.tm_min)
print("current sec:",t.tm_sec)
print("current weakday:",t.tm_wday)
print("...................")